import os
import time
import random
import subprocess
import gc
import torch
import soundfile as sf
from transformers import MusicgenForConditionalGeneration, MusicgenProcessor
from diffusers import StableDiffusionPipeline
import edge_tts

# =========================
# ENV / CONFIG
# =========================
STREAM_KEY = os.environ.get("TWITCH_STREAM_KEY")
if not STREAM_KEY:
    raise RuntimeError("TWITCH_STREAM_KEY is not set")

RTMP_URL = f"rtmp://live.twitch.tv/app/{STREAM_KEY}"

WORKDIR = "/workspace/airadio/data"
os.makedirs(WORKDIR, exist_ok=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"⚙️ Device: {DEVICE}")

# =========================
# LOAD MODELS
# =========================
print("⏳ Loading MusicGen...")
processor = MusicgenProcessor.from_pretrained("facebook/musicgen-small")
music_model = MusicgenForConditionalGeneration.from_pretrained(
    "facebook/musicgen-small",
    torch_dtype=torch.float32
).to(DEVICE)
music_model.eval()

print("⏳ Loading Stable Diffusion...")
sd = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to(DEVICE)
sd.safety_checker = None

# =========================
# PROMPTS
# =========================
MUSIC_PROMPTS = [
    "lo-fi hip hop beats, chill, rain",
    "cyberpunk synthwave, neon night",
    "ambient space drone, calm",
    "deep house, melodic, focus",
    "retrowave driving at night"
]

DJ_PHRASES = [
    "You are listening to AI Radio.",
    "Generated by code, enjoyed by humans.",
    "Relax and enjoy the vibe.",
    "Broadcasting live from the cloud.",
    "Infinite stream active."
]

# =========================
# HELPERS
# =========================
def cleanup():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        try:
            torch.cuda.ipc_collect()
        except Exception:
            pass

# =========================
# GENERATORS
# =========================
def gen_music(prompt, out_wav, retries=3):
    cleanup()
    inputs = processor(text=[prompt], return_tensors="pt").to(DEVICE)

    for attempt in range(retries):
        try:
            with torch.no_grad():
                audio = music_model.generate(
                    **inputs,
                    max_new_tokens=700,
                    do_sample=False
                )
            sr = music_model.config.audio_encoder.sampling_rate
            sf.write(out_wav, audio[0,]()_
